spring:
  profiles:
    active: dev


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  default-produces-media-type: application/json

server:
  servlet:
    context-path: /api/v1/